global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: wellness-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api:8080

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090

remote_write:
  - url: "https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push"
    basic_auth:
      username: "3585652"
      password_file: /etc/prometheus/wellness-monitoring-token
